<?php

$plugin = array(
  'title' => t('Zen’s default Panels Everywhere layout'),
  'category' => t('Columns: 3'),
  'icon' => 'icon.png',
  'theme' => 'zen_main',
  'regions' => array(
    'header' => t('Header'),
    'navigation' => t('Navigation bar'),
    'highlighted' => t('Highlighted'),
    'content' => t('Content'),
    'sidebar_first' => t('First sidebar'),
    'sidebar_second' => t('Second sidebar'),
    'footer' => t('Footer'),
  ),
);
