# frozen_string_literal: true

source "https://rubygems.org"
gem "breakpoint"
gem "chroma"
gem "support-for"
gem "typey"
gem "zen-grids"
gem "compass", '~>1.0.3'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
